[workspace]
resolver = "2"
members = [
    "maxima-bootstrap",
    "maxima-cli",
    "maxima-lib",
    "maxima-native",
    "maxima-service",
    "maxima-tui",
    "maxima-ui",
    "maxima-resources",
]

[profile.release]
strip = true
